default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

test:
  <<: *default
  database: pacifica_test

development:
  <<: *default
  database: pacifica_development

production:
  <<: *default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  database: <%= ENV.fetch("DB_DATABASE") { 'pacifica_production' }%>
  host: <%= ENV['DB_HOSTNAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
